[build-system]
requires = ["setuptools==82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "instruments-of-thought"
version = "0.0.1"
authors = [
    {name="Machina Ratiocinatrix", email="machina.ratio@gmail.com"},
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"}
]
description = "Instruments-of-Thought ..."
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
keywords = ["instruments-of-thought"]
dependencies = [
    "pyyaml == 6.0.3"
]

[project.scripts]
instruments-of-thought = "instruments_of_thought.cli:run"

[project.urls]
"Homepage" = "https://github.com/instruments-for-thought/instruments-of-thought"

[dependency-groups]
dev = ["pytest>=8.0.0"]